### ISSUE TITLE
Scaled Units Supercession in User Interface

### ISSUE THREAD

**Issue by tarmanan** [ni/niveristand-scan-engine-ethercat-custom-device#104] opened 2020-10-19 17:33 UTC
**Describe the bug**
Per VeriStand Help Manual, units from Scale should supercede the units associated with the channel.  

https://www.ni.com/documentation/en/veristand/19.2/manual/create-polynomial-scale/

Units supercession carries through to data log file [ie, TDMS], but does not change annotation of units in User Interface. 

**To Reproduce**
1. Create Polynomial scale and specify units
2.  Map Scale to channel via Scale Mappings
3.  View Channel in User Interface

**Expected behavior**
User Interface displays channel with units specified in Scale, rather than units from "Channel Settings"

**Screenshots**
![image](https://user-images.githubusercontent.com/46938263/96490600-0d302300-120f-11eb-99f4-c46d260e2762.png)
![image](https://user-images.githubusercontent.com/46938263/96490611-128d6d80-120f-11eb-9dd1-587a31b0320a.png)
![image](https://user-images.githubusercontent.com/46938263/96490635-17522180-120f-11eb-99c0-1407da67d0a9.png)
![image](https://user-images.githubusercontent.com/46938263/96490670-1faa5c80-120f-11eb-96aa-9a0b40039209.png)
![image](https://user-images.githubusercontent.com/46938263/96490679-233de380-120f-11eb-9b3d-7b48135ea594.png)

**Desktop (please complete the following information):**
VeriStand 2019 R3
NI Scan Engine and EtherCAT for VeriStand 2019 v. 20.3.1
cRIO-9068
OS:  Linux

**Additional context**

**Comment by rtzoeller** [comment] 2020-10-19 18:54
Thanks for filing this @tarmanan!

Since this has to do with VeriStand, rather than the Scan Engine EtherCAT custom device specifically, I am going to close this issue.

We've created an internal bug for VeriStand tracking this issue, with ID 1155690.

**Closed by rtzoeller** 2020-10-19 18:54 UTC
Labels: bug

**Comment by rtzoeller** [comment] 2020-10-30 19:58
@tarmanan I've been unable to reproduce this with VeriStand 2019 R3 - are there any more specific reproducing steps you can share?

**Comment by rtzoeller** [comment] 2020-11-04 23:26
@tarmanan any update on this?

**Comment by tarmanan** [comment] 2020-11-05 14:05
@rtzoeller Thank you for following up.  I attempted to reproduce this again in a new VeriStand 2019 R3 project [Scan Engine EtherCAT custom device v. 20.3.1] today and was unsuccessful as well.
